### ISSUE TITLE
make web/dhcp server robust

### ISSUE THREAD

**Issue by amitsi** [amitsi/onieztp#23]
auto-start if crashed (dhcpd/webserver)
allow logging of dhcpd in syslog or dmesg so more detailed troubleshooting can be done
Allow pull of log files preferably through a single syslog type file  containing(syslog, dhcp.conf) from the HTML itself

**Comment by amitsi** [comment]
Same with flask

**Comment by amitsi** [comment]
already there

**Comment by venkytv** [comment]
Moved the logging requirement to issue #36 .

Service management of dhcpd/webserver/flask is handled by supervisor within the container, which takes of restarting them in case of a crash.

Check status of supervised services within the container using this:
# supervisorctl status
