### ISSUE TITLE
Can't build it on a Mac unless I am using wrong syntax?

### ISSUE THREAD

**Issue by amitsi** [amitsi/onieztp#3]
amitsi-5:~ amitsingh$ docker build https://github.com/amitsi/onieztp/blob/master/onie/docker/
Downloading build context from remote url: https://github.com/amitsi/onieztp/blob/master/onie/docker/  40.66kB
Sending build context to Docker daemon   42.5kB
Error response from daemon: Dockerfile parse error line 7: unknown instruction: <!DOCTYPE
amitsi-5:~ amitsingh$ docker build https://github.com/amitsi/onieztp/blob/master/onie/docker/Dockerfile
Downloading build context from remote url: https://github.com/amitsi/onieztp/blob/master/onie/docker/Dockerfile  43.41kB
Sending build context to Docker daemon  45.06kB
Error response from daemon: Dockerfile parse error line 7: unknown instruction: <!DOCTYPE
amitsi-5:~ amitsingh$

**Comment by venkytv** [comment]
Building directly from git requires a slightly different URL format:

`docker build 'https://github.com/amitsi/onieztp.git#:onie/docker'`
