### ISSUE TITLE
create a way for backup/upgrade/migrate

### ISSUE THREAD

**Issue by amitsi** [amitsi/onieztp#34]
could be through script or separate volume...if separate volume the steps could be automated in ashish's install script

https://github.com/amitsi/onieztp/blob/master/onie/scripts/pn_docker_setup.sh

**Comment by amitsi** [comment]
I was thinking this we dont have to worry but we have people who want to use it and upgrade to test...maybe we address this after the others in the list marked help wanted

**Comment by venkytv** [comment]
Done.  DB migrations are supported now.
