### ISSUE TITLE
option-url Missing

### ISSUE THREAD

**Issue by amitsi** [amitsi/onieztp#4]
a Place for the option-url for ONIE is missing

host onie3 {

  hardware ethernet 8C:EA:1B:36:B7:33;

  fixed-address 10.9.31.213;

  option host-name "onie3";

  **option default-url="http://10.9.8.196/images/onie-installer";**

}

**Comment by venkytv** [comment]
Brought the default URL option back in 7e1287ec94b2cbda508753f574ae3acbcc9b2524.  Before this, it was being computed based on the IP of the docker.  Now, if the default URL is not provided, we fallback to the old method.
