### ISSUE TITLE
dhcp IP/MAC search section is missing in the latest build

### ISSUE THREAD

**Issue by amitsi** [amitsi/onieztp#42]

**Comment by amitsi** [comment]
<img width="1008" alt="screen shot 2017-10-28 at 4 44 56 pm" src="https://user-images.githubusercontent.com/10914373/32139497-627ff1c8-bbff-11e7-9d87-b2896968e59c.png">

**Comment by venkytv** [comment]
By default, the search box was configured to display only if there are at least 8 rows in the table.  Have reduced that number to 2.
