### ISSUE TITLE
DHCP entry not host entry

### ISSUE THREAD

**Issue by amitsi** [amitsi/onieztp#5]
<img width="736" alt="screen shot 2017-10-13 at 11 01 22 am" src="https://user-images.githubusercontent.com/10914373/31559575-f7d18116-b005-11e7-86bf-17618e03bae7.png">

we are creating 2 files....dhcpd.conf (for ONIE need option-url) and host file (for Ansible)
This section should be called the add DHCP host entry (populate the dhcpd.conf file)

Allow a checkbox button next to hostname to create a host file for ansible

**Comment by venkytv** [comment]
Added this in 58a0716567d0b644739e43a194c7ba421fce0027.
