### ISSUE TITLE
Can the fields be auto-populated based on host=eth0?

### ISSUE THREAD

**Issue by amitsi** [amitsi/onieztp#6]
<img width="732" alt="screen shot 2017-10-13 at 11 06 34 am" src="https://user-images.githubusercontent.com/10914373/31559759-b1e7a9ea-b006-11e7-828e-20b4ab44b029.png">

Also please note this is the generic setting we will had a specific IP to specific MAC in the section below this section (option-url missing)

**Comment by venkytv** [comment]
Added support for this in 7e1287ec94b2cbda508753f574ae3acbcc9b2524.  Subnet, subnet mask and broadcast address now get automatically computed based on the chosen DHCP interface.
